CA_ADMIN_NAME=
CA_ADMIN_PASSWORD=

ROOT_MSP=
ROOT_NUMBER=
ROOT_PASSWORD=

USER_WALLET_STORAGE=
COURT_WALLET_STORAGE=

JWE_SECRET=

export CA_ADMIN_NAME CA_ADMIN_PASSWORD ROOT_MSP ROOT_NUMBER ROOT_PASSWORD USER_WALLET_STORAGE COURT_WALLET_STORAGE JWE_SECRET
